<?php

require_once('../include/sangaku.inc');
 
$students = array(
 array("Adamek","Rafal","eia20rza"),
 array("Adetuyole","Nelson","eia19noa"),
 array("Albastaki","Mohammed Hussain","eia20mma"),
 array("Alcachupas","Aeron","elc20aa"),
 array("Aldarmaki","Ahmed Mousa","elc20ama"),
 array("Alfarsi","Fatima Ali Mohamed Ahmed","eid20fa"),
 array("Alhamar","Majed Khaled","ela20mma"),
 array("Alhosani","Fatima Salem Mohamed Binsalem","eic20fa"),
 array("Aljallaf","Ahmad Abdulla Sultan Mohamed","elg20aa"),
 array("Alketbi","Ahmed Alsharqi Obaid Surour","ele20aa"),
 array("Alksnin","Blazej","eia19bja"),
 array("Allen","James","eif19ja"),
 array("Allison","Thomas","eia20ta"),
 array("Almendra Abrantes","Joana","ela20ja"),
 array("Alotaibi","Omar Mohammed O","ela20oa"),
 array("Alqaddoumi","Sami O M J","cic20sa"),
 array("Andrew","Rhodri","eic19ra"),
 array("Annauth","Aappteshaa","eld20aa"),
 array("Asad","Muhammad","eib20ma"),
 array("Askari","Mohammad","eie19ma"),
 array("Azevedo Furtado","Joao","eia20ja"),
 array("Azzam","Julian","eib20ja"),
 array("Azzopardi","Leonardo","eia19lja"),
 array("Baldwin","Charles","ela19cb"),
 array("Ball","Rachel","ela19rfb"),
 array("Barber","Jai","eie20jb"),
 array("Barnes","Aleks","eia20ab"),
 array("Bell","Aidan","eid19ab"),
 array("Bell","Callum","eia19cjb"),
 array("Bell","Finlay","eia20fb"),
 array("Benn","Zoe","ela20zb"),
 array("Berlanga-Reyes","David","eia19djb"),
 array("Berry","Den","eia19db"),
 array("Birks","Louis","eib19lb"),
 array("Blazey","Grace","eia19grb"),
 array("Bodurov","Kristiyan","ela20kb"),
 array("Branigan","Ella","eid19eb"),
 array("Branson","Oliver","eia20ob"),
 array("Briggs","Sarah","eia19smb"),
 array("Brookes","William","eia19wb"),
 array("Brosnan-Wren","James","eia19jmb"),
 array("Brown","James","ela20jab"),
 array("Brownlee","Alick","eia19aeb"),
 array("Buck","Jonathan","eia20jdb"),
 array("Buckley","Luke","ela20lb"),
 array("Byrne","Michael","phb19mjb"),
 array("Can","Neslisah","eia20nc"),
 array("Carslaw Tricot","Sean","eia19sfc"),
 array("Carty","William","pha17wc"),
 array("Chan","Ching","pha19chc"),
 array("Chan","Ho","eia20hyc"),
 array("Chan","Hui Chun","eib20hc"),
 array("Chanda","Vivek","coa20vc"),
 array("Chantzaras","Leonidas","eia20lac"),
 array("Charles","Moegammad","eia19mac"),
 array("Chen","Yuening","elb20yc"),
 array("Clendon","James","eib19jsc"),
 array("Cochrane","Daniel","eia20dec"),
 array("Colamussi","Emily","eib19ejc"),
 array("Coleman","Zack","eia20zjc"),
 array("Cookson","Thomas","ela20tec"),
 array("Cooper","Holly","eia19hjc"),
 array("Crossley","Lexi","eib19lsc"),
 array("Dai","Xiangrong","ela20xd"),
 array("Darkwah","Demara","eia19dod"),
 array("Davies","Cora","eia19ced"),
 array("De Beaux","Charles","ela18ccd"),
 array("Dixon","Luke","mec19ld"),
 array("Dobson","Cavanagh","eia19chd"),
 array("Dolman","Luke","eia19lad"),
 array("Earl","Joshua","eia20je"),
 array("East","Matthew","eia19me"),
 array("Edmunds","Lewis","eib19le"),
 array("Enabulele","Oluwatomisin","eia19oe"),
 array("Eshraghi-Yazdi","Kian","eia20ke"),
 array("Facun","Hannah","eia18hlf"),
 array("Findlay","Thomas","eib20tf"),
 array("Forster","William","eia19whf"),
 array("Fraser","Charlotte","elb19cf"),
 array("Gale","Tristan","eia20txg"),
 array("Gharssalla","Zanoubia","eia19zg"),
 array("Ghera","Camelia","eia18cag"),
 array("Gracia","Hector","eia20hg"),
 array("Graham","Brandon","eia19bgg"),
 array("Greany","Colm","eia19cmg"),
 array("Grindley","Thelma","eia19tlg"),
 array("Guo","Yuxuan","eia20yg"),
 array("Hadfield","Christopher","eia19cjh"),
 array("Hale","Liam","eid19lh"),
 array("Hamdy","Faris","eia19fh"),
 array("Hannah","Jack","eih19jh"),
 array("Hasnain","Ismaeel","eib19ih"),
 array("Hassannejad","Houman","eib19hh"),
 array("Hatton","Daniel","eic19dh"),
 array("Heath","Matthew","eia20mh"),
 array("Higham","Kai","eia20kh"),
 array("Higham","William","eia20wfh"),
 array("Hirota","Kenzo","ela20kh"),
 array("Ho","Chak Kiu","eic20ch"),
 array("Ho","Shu Hang","cia20sh"),
 array("Hodgson","George","eib19gh"),
 array("Holman","Peter","eia19pjh"),
 array("Hopkinson","James","ela19jhh"),
 array("Hurlock-Brown","Owen","eib19oh"),
 array("Hussaarts - Worthington","Jade","ela19jmh"),
 array("Hutchins","Edward","eia20ejh"),
 array("Imisson","Harry","eia20hmi"),
 array("Ismail","Aadam","eia19ai"),
 array("Jacob","Aaron","eib19agj"),
 array("James","Harry","eia19hj"),
 array("Jayasekera","Hettiarachchige","eia20hjj"),
 array("Jeffery","Ashley","eia19adj"),
 array("Johnson","Freya","eia19fjj"),
 array("Jones","Dominic","eia19dj"),
 array("Kanaris-Sotiriou","James","eic19jk"),
 array("Karaoguz","Ipeksu","ela20ik"),
 array("Ketkar","Tim","ela20tk"),
 array("Keynes","Peter","eia20pk"),
 array("Khalidi","Ali","eia20ak"),
 array("Khan","Mohsin","eic20mk"),
 array("Khan","Moiz","eib20mk"),
 array("Lai","Yun-Nien","elj20yl"),
 array("Langdon-Reich","Alexandra","eia19al"),
 array("Lara","Maxwell","eia20ml"),
 array("Larkin","Hazel","eia20hel"),
 array("Lee","Timothy Jaeyong","elb20tl"),
 array("Li","Tianyu","mta20tl"),
 array("Li","Yuxiao","elk20yl"),
 array("Liew","Brian","eia20byl"),
 array("Lim","Joshua Royce Siang","elf20jl"),
 array("Liu","Yuhan","eli19yl"),
 array("Liu","Zhuoyan","elg20zl"),
 array("Lu","Jiangfeng","ela20jl"),
 array("Luke","Jack","eia19jhl"),
 array("Lumley","Daniel","elb20dl"),
 array("Macarthur-Peters","Brooke","eia20bm"),
 array("Mack","Naiha","eic18nm"),
 array("Maguyon","Jeremias","eig19jm"),
 array("Mahdi","Abdullah Ahmed A","ele20am"),
 array("Malik","Sameer","eii19sm"),
 array("Malloura","Nicholas","eia20nm"),
 array("Mangham","Eliza","eia19ejm"),
 array("Martin","Oliver","eia19om"),
 array("Matareed","Ali","eif19am"),
 array("McFarlane","Elliot","eij19em"),
 array("Mcdonald","Oliver","eia20odm"),
 array("Mcgarva","Holly","eic19hm"),
 array("Mcgowan","Jozef","eia18jsm"),
 array("Mcnally","Molly","eif19mm"),
 array("Mileris","Klaidas","eib20km"),
 array("Mistry","Parisha","eia19pm"),
 array("Mitchell","Alistair","elb20am"),
 array("Mitchell","Callum","ela19cjm"),
 array("Mitrea","Ovidiu","ela20om"),
 array("Monaghan","Luke","eic19lm"),
 array("Moore","Stephen","ela20sjm"),
 array("Morgan","Dylan","eia19drm"),
 array("Morris","Georgia","eia20gem"),
 array("Mrzena","Karel","eic20km"),
 array("Mui","Weng","eia19wim"),
 array("Nacu","Andrei","eia20ain"),
 array("Needham","Lawrence","eia20lmn"),
 array("Ni","Ruichen","ela19rn"),
 array("Nixon","Marshall","eia19mrn"),
 array("Norman","James","eic19jn"),
 array("Nunes","Chad","eia19cn"),
 array("O'Connor","Oisin","eib20oo"),
 array("Oteng","Abena","eid19ao"),
 array("Pan","Zichao","ela20zp"),
 array("Papaioannou","Ioannis","eib19ip"),
 array("Parkin","Annabelle","eic19ajp"),
 array("Parkinson","George","eib19gp"),
 array("Passey","Jack","eia19jcp"),
 array("Patel","Dhwani","eic20dp"),
 array("Patel","Himesh","ela19hp"),
 array("Patterson","Oscar","eia19ojp"),
 array("Perrin","Daniel","eia20dap"),
 array("Pett","Samuel","eia19sdp"),
 array("Pilcher","Rebecca","eia19rgp"),
 array("Pitts","Jonathan","eie19jp"),
 array("Popat","Divyen","eia20djp"),
 array("Porter","Isaac","pha20ip"),
 array("Potter","Samuel","ela20sjp"),
 array("Power","Charles","eib19cp"),
 array("Price","Emily","eic19ep"),
 array("Price","Finlay","eia19fp"),
 array("Rami Ibrahim Al Ramahi","Yazan","ela20yr"),
 array("Reeves","Megan","eib19mar"),
 array("Rigo","Balazs","eid19br"),
 array("Roberts","Thomas","eia19twr"),
 array("Robertson","Madeleine","eia20mer"),
 array("Roejkjaer","Anika","eia20ar"),
 array("Roome","Oliver","meb19or"),
 array("Sacks","Jenna","eid20js"),
 array("Saji","Gershom","eia18gs"),
 array("Salkeld","Mathew","elb19ms"),
 array("Scutt","Harry","eia18has"),
 array("Senior","Graeme","eic20gs"),
 array("Shaikh","Nuhaa","eia20nns"),
 array("Shao","Weijun","elb20ws"),
 array("Sheet","Ali","eif20as"),
 array("Shoko","Tinashe","eie18ts"),
 array("Smith","Cameron","eia18cds"),
 array("Smith","Dylan","eie19ds"),
 array("Smith","Thomas","eig18ts"),
 array("Smith","Thomas","eid19ts"),
 array("Socha","Marcin","eia20ms"),
 array("Spurr","Luke","eia19lws"),
 array("Stacey","Joe","eic20js"),
 array("Suzuki","Mathys","eic20ms"),
 array("Sweeney","Anthony","cic19as"),
 array("Swinscoe","Thomas","eij18ts"),
 array("Tang","Li","ela20lt"),
 array("Taylor","Robyn","eib19rt"),
 array("Thompson","Joseph","eia19jtt"),
 array("Tian","Hezi","ela19ht"),
 array("Tomlinson","Ashley","eib19at"),
 array("Tooley","Callum","eib19ct"),
 array("Valcic","Vid","eib19vv"),
 array("Vlad","Andra-Maria","eia19amv"),
 array("Walker","Benjamin","eia20bw"),
 array("Walker","Sam","ela19sw"),
 array("Walker","Scott","elb19sw"),
 array("Wang","Xiaochen","ela20xw"),
 array("Ward","Niall","eia20nw"),
 array("Ward","Toby","eia19tw"),
 array("Welch","Alexander","eia19aw"),
 array("Wheeler","Nathan","eib20nw"),
 array("Williams","Caleb","eic19cw"),
 array("Wisniewska","Martyna","eia20mw"),
 array("Wood","George","eib18gaw"),
 array("Woodall","William","elb18ww"),
 array("Worobij","Wojciech","eia19ww"),
 array("Wright","Henry","eia19hcw"),
 array("Wynne","Ryan","eia19rjw"),
 array("Xie","Youheng","elb20yx"),
 array("Xie","Ziyu","ela19zx"),
 array("Xu","Jiaxin","ela20jx"),
 array("Yang","Juncheng","eib20jy"),
 array("Young","Maxim","eia20my"),
 array("Yu","Chongye","eib20cy"),
 array("Zahid","Amna","eia20akz"),
 array("Zhang","Zhijian","eia20zz"),
 array("Zhu","Baichuan","ela20bz")
);

foreach($students as $s0) {
 $ss = $sangaku->load_where('user',"x.username={$s0[2]}");
 if (! $ss) {
  $s = $sangaku->new_object('user');
  $s->surname  = $s0[0];
  $s->forename = $s0[1];
  $s->username = $s0[2];
  $s->save();

  $m = $sangaku->new_object('tutorial_group_student')
 }
}
